#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

FOUNDATION_EXPORT NSErrorDomain const IMPAPIKeyStoreErrorDomain;

typedef NS_ERROR_ENUM(IMPAPIKeyStoreErrorDomain, IMPAPIKeyStoreErrorCode){
    IMPAPIKeyStoreErrorInvalidArgument = 1,
    IMPAPIKeyStoreErrorDatabaseUnavailable,
    IMPAPIKeyStoreErrorDatabaseBusy,
    IMPAPIKeyStoreErrorDatabaseCorrupt,
    IMPAPIKeyStoreErrorSchemaMismatch,
    IMPAPIKeyStoreErrorCryptography,
    IMPAPIKeyStoreErrorAuthenticationFailed,
    IMPAPIKeyStoreErrorAuthorizationFailed,
    IMPAPIKeyStoreErrorActiveAdminExists,
    IMPAPIKeyStoreErrorLastActiveAdmin,
    IMPAPIKeyStoreErrorNotFound,
    IMPAPIKeyStoreErrorConflict,
    IMPAPIKeyStoreErrorInvalidState,
};

typedef NSString *IMPAPIKeyScope NS_TYPED_EXTENSIBLE_ENUM;
FOUNDATION_EXPORT IMPAPIKeyScope const IMPAPIKeyScopeMessagesRead;
FOUNDATION_EXPORT IMPAPIKeyScope const IMPAPIKeyScopeMessagesSend;
FOUNDATION_EXPORT IMPAPIKeyScope const IMPAPIKeyScopeAdmin;

FOUNDATION_EXPORT NSString *const IMPAPIKeyCreationRecordKey;
FOUNDATION_EXPORT NSString *const IMPAPIKeyCreationTokenKey;

@interface IMPAPIKeyRecord : NSObject

@property (nonatomic, copy, readonly) NSString *uuid;
@property (nonatomic, copy, readonly) NSString *name;
/// Non-secret display prefix (`imp_` plus the first eight encoded characters).
@property (nonatomic, copy, readonly) NSString *keyPrefix;
@property (nonatomic, copy, readonly) NSArray<IMPAPIKeyScope> *scopes;
@property (nonatomic, copy, readonly) NSDate *createdAt;
@property (nonatomic, copy, readonly, nullable) NSDate *expiresAt;
@property (nonatomic, copy, readonly, nullable) NSDate *revokedAt;
@property (nonatomic, copy, readonly, nullable) NSDate *lastUsedAt;

/// The admin scope implies every supported scope.
- (BOOL)hasScope:(IMPAPIKeyScope)scope;

@end

typedef NS_ENUM(NSInteger, IMPIdempotencyState) {
    IMPIdempotencyStateInProgress = 1,
    IMPIdempotencyStateSucceeded,
    IMPIdempotencyStateAmbiguous,
    IMPIdempotencyStateFailed,
};

typedef NS_ENUM(NSInteger, IMPIdempotencyDisposition) {
    /// This caller atomically created the record and owns the operation.
    IMPIdempotencyDispositionNew = 1,
    /// The same request was completed previously; replay the stored response.
    IMPIdempotencyDispositionReplay,
    /// The key exists with a different request hash.
    IMPIdempotencyDispositionConflict,
    /// The same request is currently executing.
    IMPIdempotencyDispositionInProgress,
    /// The operation may have taken effect and must not be retried automatically.
    IMPIdempotencyDispositionAmbiguous,
};

@interface IMPIdempotencyRecord : NSObject

@property (nonatomic, copy, readonly) NSString *principalUUID;
@property (nonatomic, copy, readonly) NSString *key;
/// Stable UUID generated by the first successful claim and returned on every replay.
@property (nonatomic, copy, readonly) NSString *operationUUID;
@property (nonatomic, readonly) IMPIdempotencyState state;
@property (nonatomic, readonly) IMPIdempotencyDisposition disposition;
@property (nonatomic, strong, readonly, nullable) NSNumber *responseStatus;
@property (nonatomic, copy, readonly, nullable) NSData *responseBody;
@property (nonatomic, copy, readonly) NSDate *createdAt;
@property (nonatomic, copy, readonly) NSDate *updatedAt;

@end

typedef NS_ENUM(NSInteger, IMPAuditPhase) {
    IMPAuditPhaseAttempted = 1,
    IMPAuditPhaseFinal,
};

/// Privacy-safe request metadata. It never contains message content, targets, credentials, or hashes.
@interface IMPAuditRecord : NSObject

@property (nonatomic, copy, readonly) NSString *requestUUID;
@property (nonatomic, copy, readonly, nullable) NSString *keyUUID;
@property (nonatomic, copy, readonly, nullable) NSString *targetKeyUUID;
@property (nonatomic, copy, readonly) NSString *source;
@property (nonatomic, copy, readonly) NSString *action;
@property (nonatomic, readonly) IMPAuditPhase phase;
@property (nonatomic, strong, readonly, nullable) NSNumber *status;
@property (nonatomic, strong, readonly, nullable) NSNumber *durationMilliseconds;
@property (nonatomic, copy, readonly) NSDate *createdAt;

@end

@interface IMPAPIKeyStore : NSObject

- (nullable instancetype)initWithPath:(NSString *)path
                                error:(NSError *_Nullable *_Nullable)error NS_DESIGNATED_INITIALIZER;
- (instancetype)init NS_UNAVAILABLE;

/// Returns the plaintext key exactly once under IMPAPIKeyCreationTokenKey.
- (nullable NSDictionary<NSString *, id> *)bootstrapAdminNamed:(NSString *)name
                                                   expiresDays:(NSUInteger)expiresDays
                                                         error:(NSError *_Nullable *_Nullable)error;

/// Returns { IMPAPIKeyCreationRecordKey: IMPAPIKeyRecord,
///           IMPAPIKeyCreationTokenKey: NSString }. Only the SHA-256 key hash is persisted.
- (nullable NSDictionary<NSString *, id> *)createKeyNamed:(NSString *)name
                                                   scopes:(NSArray<IMPAPIKeyScope> *)scopes
                                                expiresAt:(nullable NSDate *)expiresAt
                                                actorUUID:(NSString *)actorUUID
                                                    error:(NSError *_Nullable *_Nullable)error;

/// Authenticates an `imp_` token, rejects expired/revoked keys, and updates lastUsedAt.
/// All credential failures use IMPAPIKeyStoreErrorAuthenticationFailed.
- (nullable IMPAPIKeyRecord *)authenticateToken:(NSString *)token error:(NSError *_Nullable *_Nullable)error;

- (nullable NSArray<IMPAPIKeyRecord *> *)listKeysWithLimit:(NSUInteger)limit error:(NSError *_Nullable *_Nullable)error;

/// Returns metadata for one API key UUID. Plaintext credentials and hashes are never returned.
- (nullable IMPAPIKeyRecord *)keyWithUUID:(NSString *)uuid error:(NSError *_Nullable *_Nullable)error;

/// The actor must be an active admin. Revoking the final active admin is refused.
- (BOOL)revokeKeyUUID:(NSString *)uuid actorUUID:(NSString *)actorUUID error:(NSError *_Nullable *_Nullable)error;

/// Convenience helper for producing the required 32-byte request digest.
+ (NSData *)SHA256ForData:(NSData *)data;

/// Atomically claims a (principal UUID, Idempotency-Key) pair. requestHash must be 32 bytes.
- (nullable IMPIdempotencyRecord *)claimForPrincipalUUID:(NSString *)principalUUID
                                                     key:(NSString *)key
                                             requestHash:(NSData *)requestHash
                                                   error:(NSError *_Nullable *_Nullable)error;

/// Converts claims left in progress by a previous server process to non-retriable ambiguous records.
/// Call only after this process exclusively owns the configured listening socket.
- (BOOL)prepareForServerStartup:(NSError *_Nullable *_Nullable)error;

/// Completes an owned in-progress claim. State must be succeeded, ambiguous, or failed.
- (BOOL)completeForPrincipalUUID:(NSString *)principalUUID
                             key:(NSString *)key
                     requestHash:(NSData *)requestHash
                   operationUUID:(NSString *)operationUUID
                           state:(IMPIdempotencyState)state
                  responseStatus:(NSInteger)responseStatus
                    responseBody:(NSData *)responseBody
                           error:(NSError *_Nullable *_Nullable)error;

/// Inserts one attempted or final audit row. Repeating an identical row is idempotent;
/// changing an existing (request UUID, phase) row is a conflict.
- (BOOL)recordAuditForRequestUUID:(NSString *)requestUUID
                          keyUUID:(nullable NSString *)keyUUID
                    targetKeyUUID:(nullable NSString *)targetKeyUUID
                           source:(NSString *)source
                           action:(NSString *)action
                            phase:(IMPAuditPhase)phase
                           status:(nullable NSNumber *)status
             durationMilliseconds:(nullable NSNumber *)durationMilliseconds
                            error:(NSError *_Nullable *_Nullable)error;

/// Returns newest-first audit metadata. limit must be between 1 and 1000.
- (nullable NSArray<IMPAuditRecord *> *)auditRecordsWithLimit:(NSUInteger)limit
                                                        error:(NSError *_Nullable *_Nullable)error;

@end

NS_ASSUME_NONNULL_END
